# Generated by Django 3.1.8 on 2021-04-29 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationHookPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='automations_automationhookplugin', serialize=False, to='cms.cmsplugin')),
                ('automation', models.CharField(max_length=128, verbose_name='Automatisierung')),
                ('operation', models.IntegerField(choices=[(0, 'Automatisierung starten'), (1, 'Automatisierungs-Rückruf')], default=1)),
                ('message', models.CharField(blank=True, max_length=128, verbose_name='Rückruf-Nachricht')),
                ('kwargs', models.JSONField(blank=True, default=dict, verbose_name='kwargs zur Erstellung der Automatisierung')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AutomationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_class', models.CharField(max_length=256, verbose_name='Prezess-Klasse')),
                ('finished', models.BooleanField(default=False, verbose_name='Beendet')),
                ('data', models.JSONField(default=dict, verbose_name='Daten')),
                ('paused_until', models.DateTimeField(null=True, verbose_name='Pausiert bis')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTasksPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='automations_automationtasksplugin', serialize=False, to='cms.cmsplugin')),
                ('template', models.CharField(choices=[('automations/includes/task_list.html', 'Default template')], default='automations/includes/task_list.html', max_length=128, verbose_name='Template')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AutomationTaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=256, verbose_name='Status')),
                ('locked', models.IntegerField(default=0, verbose_name='Gesperrt')),
                ('interaction_permissions', models.JSONField(default=list, help_text='List of permissions of the form app_label.codename', verbose_name='Required permissions')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('message', models.CharField(blank=True, max_length=128, verbose_name='Nachricht')),
                ('result', models.JSONField(blank=True, default=dict, null=True, verbose_name='Ergebnis')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automations.automationmodel')),
                ('interaction_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Assigned group')),
                ('interaction_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Assigned user')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automations.automationtaskmodel', verbose_name='Vorherige Aufgabe')),
            ],
        ),
    ]
