# Generated by Django 3.1.8 on 2021-05-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_auto_20210511_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationmodel',
            name='key',
            field=models.CharField(default='', max_length=64, verbose_name='_Unique hash'),
        ),
    ]
