# Generated by Django 3.1.8 on 2021-12-29 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automations', '0006_auto_20211121_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationmodel',
            name='automation_class',
            field=models.CharField(max_length=256, verbose_name='Prezess-Klasse'),
        ),
        migrations.AlterField(
            model_name='automationmodel',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Daten'),
        ),
        migrations.AlterField(
            model_name='automationmodel',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Beendet'),
        ),
        migrations.AlterField(
            model_name='automationmodel',
            name='key',
            field=models.CharField(default='', max_length=64, verbose_name='Eindeutiger Hash-Wert'),
        ),
        migrations.AlterField(
            model_name='automationmodel',
            name='paused_until',
            field=models.DateTimeField(null=True, verbose_name='Pausiert bis'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='interaction_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Zugewiesene Gruppe'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='interaction_permissions',
            field=models.JSONField(default=list, help_text='Liste von Permissions in der Form <code>app_label.codename</code>', verbose_name='Benötigte Permissions'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='interaction_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesener Nutzer'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='locked',
            field=models.IntegerField(default=0, verbose_name='Gesperrt'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='message',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nachricht'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automations.automationtaskmodel', verbose_name='Vorherige Aufgabe'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='requires_interaction',
            field=models.BooleanField(default=False, verbose_name='Verlangt Interaktion'),
        ),
        migrations.AlterField(
            model_name='automationtaskmodel',
            name='result',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Ergebnis'),
        ),
    ]
