# Generated by Django 3.1.8 on 2021-05-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_automations', '0002_auto_20210506_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationhookplugin',
            name='automation',
            field=models.CharField(max_length=128, verbose_name='Automation'),
        ),
        migrations.AlterField(
            model_name='automationhookplugin',
            name='operation',
            field=models.IntegerField(choices=[(0, 'Start automaton'), (1, 'Send message to automation'), (2, 'Broadcast message to all automations')], default=1, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='automationhookplugin',
            name='token',
            field=models.CharField(blank=True, max_length=128, verbose_name='Optional token'),
        ),
        migrations.AlterField(
            model_name='automationstatusplugin',
            name='template',
            field=models.CharField(max_length=128, verbose_name='Task data'),
        ),
    ]
