# Generated by Django 3.1.8 on 2022-01-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_automations', '0006_auto_20211229_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationhookplugin',
            name='automation',
            field=models.CharField(max_length=128, verbose_name='Automation'),
        ),
        migrations.AlterField(
            model_name='automationhookplugin',
            name='operation',
            field=models.IntegerField(choices=[(0, 'Automatisierung starten'), (1, 'Nachricht an Automatisierung senden'), (2, 'Nachrichten-Broadcast an alle Automatisierungen')], default=1, verbose_name='Kommando'),
        ),
        migrations.AlterField(
            model_name='automationstatusplugin',
            name='template',
            field=models.CharField(max_length=128, verbose_name='Aufgaben-Datensatz'),
        ),
    ]
